import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { portraitSvg } from "#/lib/portrait";
import { parseRosterCsv, serializePlayer } from "#/lib/roster";
import type { Player } from "#/lib/player";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = resolve(root, "src/data/players.generated.ts");
const seedPath = resolve(root, "src/data/roster.seed.csv");
const publicDir = resolve(root, "public");

loadDotEnv(resolve(root, ".env"));

const csv = await loadCsv();
if (!csv) {
  if (!existsSync(outPath)) {
    throw new Error(
      "Manca ROSTER_SHEET_CSV_URL e non c'è lo snapshot src/data/players.generated.ts",
    );
  }
  console.log("No ROSTER_SHEET_CSV_URL — keeping snapshot");
  process.exit(0);
}

const players = parseRosterCsv(csv);
if (players.length === 0) {
  if (!existsSync(outPath)) {
    throw new Error("CSV rosa vuoto e snapshot assente");
  }
  console.log("CSV rosa senza righe valide — keeping snapshot");
  process.exit(0);
}

ensurePortraits(players);
const withPhotos = attachPhotos(players);
writeFileSync(outPath, renderPlayersModule(withPhotos));
console.log(`Wrote ${withPhotos.length} players → ${outPath}`);

async function loadCsv(): Promise<string | null> {
  const fromArg = argValue("--from");
  if (fromArg) {
    return readFileSync(resolve(root, fromArg), "utf8");
  }
  const url = process.env.ROSTER_SHEET_CSV_URL?.trim();
  if (!url) {
    if (existsSync(outPath)) {
      return null;
    }
    if (existsSync(seedPath)) {
      console.log("No ROSTER_SHEET_CSV_URL — bootstrapping snapshot from seed CSV");
      return readFileSync(seedPath, "utf8");
    }
    return null;
  }
  if (url.startsWith("http://") || url.startsWith("https://")) {
    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(`Roster CSV HTTP ${res.status}`);
    }
    return await res.text();
  }
  const filePath = url.startsWith("file://") ? fileURLToPath(url) : resolve(root, url);
  return readFileSync(filePath, "utf8");
}

function attachPhotos(list: Player[]): Player[] {
  return list.map((player) => {
    const png = `players/${player.slug}.png`;
    const svg = `players/${player.slug}.svg`;
    if (existsSync(resolve(publicDir, png))) {
      return { ...player, photo: png };
    }
    if (existsSync(resolve(publicDir, svg))) {
      return { ...player, photo: svg };
    }
    return serializePlayer({ ...player, photo: undefined });
  });
}

function ensurePortraits(list: Player[]) {
  const dir = resolve(publicDir, "players");
  mkdirSync(dir, { recursive: true });
  for (const player of list) {
    const png = resolve(dir, `${player.slug}.png`);
    const svg = resolve(dir, `${player.slug}.svg`);
    if (existsSync(png) || existsSync(svg)) {
      continue;
    }
    writeFileSync(svg, portraitSvg(player));
  }
}

function renderPlayersModule(list: Player[]): string {
  const body = JSON.stringify(list.map(serializePlayer), null, 2);
  return `/* generated by scripts/ingest-roster.ts — do not edit by hand */
import type { Player } from "#/lib/player";

export const players: Player[] = ${body};
`;
}

function argValue(flag: string): string | undefined {
  const index = process.argv.indexOf(flag);
  if (index < 0) {
    return undefined;
  }
  return process.argv[index + 1];
}

function loadDotEnv(path: string) {
  if (!existsSync(path)) {
    return;
  }
  const text = readFileSync(path, "utf8");
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const eq = trimmed.indexOf("=");
    if (eq < 1) {
      continue;
    }
    const key = trimmed.slice(0, eq).trim();
    if (process.env[key]) {
      continue;
    }
    process.env[key] = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, "");
  }
}
