import { existsSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { applyPortraits } from "#/lib/portraits";
import { parseRosterCsv, serializePlayer } from "#/lib/roster";
import type { Player } from "#/lib/player";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = resolve(root, "src/data/players.generated.ts");
const seedPath = resolve(root, "src/data/roster.seed.csv");
const portraitsPath = resolve(root, "src/data/portraits.csv");
const publicDir = resolve(root, "public");

loadDotEnv(resolve(root, ".env"));

const csv = await loadCsv();
let players: Player[] = [];

if (csv) {
  players = parseRosterCsv(csv);
}

if (players.length === 0) {
  if (!existsSync(outPath)) {
    throw new Error(
      "Manca ROSTER_SHEET_CSV_URL e non c'è lo snapshot src/data/players.generated.ts",
    );
  }
  console.log("No roster CSV — keeping player rows from snapshot");
  const mod = await import("#/data/players.generated");
  players = mod.players.map((player) => serializePlayer({ ...player, photo: undefined }));
}

const portraitsCsv = loadPortraitsCsv();
if (portraitsCsv) {
  players = applyPortraits(players, portraitsCsv);
}

stripGeneratedSvgs();
const withPhotos = attachPhotos(players);
writeFileSync(outPath, renderPlayersModule(withPhotos));
console.log(`Wrote ${withPhotos.length} players → ${outPath}`);

async function loadCsv(): Promise<string | null> {
  const fromArg = argValue("--from");
  if (fromArg) {
    return readFileSync(resolve(root, fromArg), "utf8");
  }
  const url = process.env.ROSTER_SHEET_CSV_URL?.trim();
  if (!url) {
    if (existsSync(seedPath)) {
      console.log("No ROSTER_SHEET_CSV_URL — using seed CSV");
      return readFileSync(seedPath, "utf8");
    }
    return null;
  }
  if (url.startsWith("http://") || url.startsWith("https://")) {
    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(`Roster CSV HTTP ${res.status}`);
    }
    return await res.text();
  }
  const filePath = url.startsWith("file://") ? fileURLToPath(url) : resolve(root, url);
  return readFileSync(filePath, "utf8");
}

function loadPortraitsCsv(): string | null {
  if (!existsSync(portraitsPath)) {
    return null;
  }
  return readFileSync(portraitsPath, "utf8");
}

function attachPhotos(list: Player[]): Player[] {
  return list.map((player) => {
    const png = `players/${player.slug}.png`;
    if (existsSync(resolve(publicDir, png))) {
      return { ...player, photo: png };
    }
    return serializePlayer({ ...player, photo: undefined });
  });
}

function stripGeneratedSvgs() {
  const dir = resolve(publicDir, "players");
  if (!existsSync(dir)) {
    return;
  }
  for (const file of readdirSync(dir)) {
    if (!file.endsWith(".svg")) {
      continue;
    }
    unlinkSync(resolve(dir, file));
  }
}

function renderPlayersModule(list: Player[]): string {
  const body = JSON.stringify(list.map(serializePlayer), null, 2);
  return `/* generated by scripts/ingest-roster.ts — do not edit by hand */
import type { Player } from "#/lib/player";

export const players: Player[] = ${body};
`;
}

function argValue(flag: string): string | undefined {
  const index = process.argv.indexOf(flag);
  if (index < 0) {
    return undefined;
  }
  return process.argv[index + 1];
}

function loadDotEnv(path: string) {
  if (!existsSync(path)) {
    return;
  }
  const text = readFileSync(path, "utf8");
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const eq = trimmed.indexOf("=");
    if (eq < 1) {
      continue;
    }
    const key = trimmed.slice(0, eq).trim();
    if (process.env[key]) {
      continue;
    }
    process.env[key] = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, "");
  }
}
