import { existsSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { applyPortraitDefaults } from "#/lib/portrait";
import { applyPortraits } from "#/lib/portraits";
import { parseRosterCsv, serializePlayer } from "#/lib/roster";
import { toGoogleSheetCsvUrl } from "#/lib/sheet-url";
import type { Player } from "#/lib/player";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = resolve(root, "src/data/players.generated.ts");
const seedPath = resolve(root, "src/data/roster.seed.csv");
const sheetUrlPath = resolve(root, "src/data/roster.sheet.url");
const portraitsPath = resolve(root, "src/data/portraits.csv");
const publicDir = resolve(root, "public");

loadDotEnv(resolve(root, ".env"));

const csv = await loadCsv();
let players: Player[] = [];

if (csv) {
  players = parseRosterCsv(csv);
}

if (players.length === 0) {
  if (!existsSync(outPath)) {
    throw new Error(
      "Manca ROSTER_SHEET_CSV_URL e non c'è lo snapshot src/data/players.generated.ts",
    );
  }
  console.log("No roster CSV — keeping player rows from snapshot");
  const mod = await import("#/data/players.generated");
  players = mod.players.map((player) => serializePlayer({ ...player, photo: undefined }));
}

const portraitsCsv = loadPortraitsCsv();
if (portraitsCsv) {
  players = applyPortraits(players, portraitsCsv);
}
players = applyPortraitDefaults(players);

stripGeneratedSvgs();
const withPhotos = attachPhotos(players);
writeFileSync(outPath, renderPlayersModule(withPhotos));
console.log(`Wrote ${withPhotos.length} players → ${outPath}`);

async function loadCsv(): Promise<string | null> {
  const fromArg = argValue("--from");
  if (fromArg) {
    return readFileSync(resolve(root, fromArg), "utf8");
  }
  const url = rosterSheetUrl();
  if (!url) {
    return readSeedCsv("No roster Sheet URL — using seed CSV");
  }
  if (url.startsWith("http://") || url.startsWith("https://")) {
    const csvUrl = toGoogleSheetCsvUrl(url);
    try {
      const res = await fetch(csvUrl);
      if (!res.ok) {
        console.warn(`Roster CSV HTTP ${res.status} — using seed CSV`);
        return readSeedCsv();
      }
      const text = await res.text();
      if (parseRosterCsv(text).length === 0) {
        console.warn("Roster Sheet is empty — using seed CSV");
        return readSeedCsv();
      }
      console.log(`Loaded roster from ${csvUrl}`);
      return text;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.warn(`Roster Sheet fetch failed (${message}) — using seed CSV`);
      return readSeedCsv();
    }
  }
  const filePath = url.startsWith("file://") ? fileURLToPath(url) : resolve(root, url);
  return readFileSync(filePath, "utf8");
}

function rosterSheetUrl(): string | undefined {
  const fromEnv = process.env.ROSTER_SHEET_CSV_URL?.trim();
  if (fromEnv) {
    return fromEnv;
  }
  if (!existsSync(sheetUrlPath)) {
    return undefined;
  }
  for (const line of readFileSync(sheetUrlPath, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#")) {
      return trimmed;
    }
  }
  return undefined;
}

function readSeedCsv(message?: string): string | null {
  if (message) {
    console.log(message);
  }
  if (!existsSync(seedPath)) {
    return null;
  }
  return readFileSync(seedPath, "utf8");
}

function loadPortraitsCsv(): string | null {
  if (!existsSync(portraitsPath)) {
    return null;
  }
  return readFileSync(portraitsPath, "utf8");
}

function attachPhotos(list: Player[]): Player[] {
  return list.map((player) => {
    const png = `players/${player.slug}.png`;
    if (existsSync(resolve(publicDir, png))) {
      return { ...player, photo: png };
    }
    return serializePlayer({ ...player, photo: undefined });
  });
}

function stripGeneratedSvgs() {
  const dir = resolve(publicDir, "players");
  if (!existsSync(dir)) {
    return;
  }
  for (const file of readdirSync(dir)) {
    if (!file.endsWith(".svg")) {
      continue;
    }
    unlinkSync(resolve(dir, file));
  }
}

function renderPlayersModule(list: Player[]): string {
  const body = JSON.stringify(list.map(serializePlayer), null, 2);
  return `/* generated by scripts/ingest-roster.ts — do not edit by hand */
import type { Player } from "#/lib/player";

export const players: Player[] = ${body};
`;
}

function argValue(flag: string): string | undefined {
  const index = process.argv.indexOf(flag);
  if (index < 0) {
    return undefined;
  }
  return process.argv[index + 1];
}

function loadDotEnv(path: string) {
  if (!existsSync(path)) {
    return;
  }
  const text = readFileSync(path, "utf8");
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const eq = trimmed.indexOf("=");
    if (eq < 1) {
      continue;
    }
    const key = trimmed.slice(0, eq).trim();
    if (process.env[key]) {
      continue;
    }
    process.env[key] = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, "");
  }
}
