/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RosaRouteImport } from './routes/rosa'
import { Route as SfidaRouteImport } from './routes/sfida'
import { Route as SfideRouteImport } from './routes/sfide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosaRoute = RosaRouteImport.update({
  id: '/rosa',
  path: '/rosa',
  getParentRoute: () => rootRouteImport,
} as any)
const SfidaRoute = SfidaRouteImport.update({
  id: '/sfida',
  path: '/sfida',
  getParentRoute: () => rootRouteImport,
} as any)
const SfideRoute = SfideRouteImport.update({
  id: '/sfide',
  path: '/sfide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rosa': typeof RosaRoute
  '/sfida': typeof SfidaRoute
  '/sfide': typeof SfideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rosa': typeof RosaRoute
  '/sfida': typeof SfidaRoute
  '/sfide': typeof SfideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rosa': typeof RosaRoute
  '/sfida': typeof SfidaRoute
  '/sfide': typeof SfideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rosa' | '/sfida' | '/sfide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rosa' | '/sfida' | '/sfide'
  id: '__root__' | '/' | '/rosa' | '/sfida' | '/sfide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RosaRoute: typeof RosaRoute
  SfidaRoute: typeof SfidaRoute
  SfideRoute: typeof SfideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosa': {
      id: '/rosa'
      path: '/rosa'
      fullPath: '/rosa'
      preLoaderRoute: typeof RosaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfida': {
      id: '/sfida'
      path: '/sfida'
      fullPath: '/sfida'
      preLoaderRoute: typeof SfidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfide': {
      id: '/sfide'
      path: '/sfide'
      fullPath: '/sfide'
      preLoaderRoute: typeof SfideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RosaRoute: RosaRoute,
  SfidaRoute: SfidaRoute,
  SfideRoute: SfideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
