/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RosaRouteImport } from './routes/rosa'
import { Route as SfidaRouteImport } from './routes/sfida'
import { Route as SfideRouteImport } from './routes/sfide'
import { Route as GiocatoriSlugRouteImport } from './routes/giocatori.$slug'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as SHostGuestRouteImport } from './routes/s.$host.$guest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosaRoute = RosaRouteImport.update({
  id: '/rosa',
  path: '/rosa',
  getParentRoute: () => rootRouteImport,
} as any)
const SfidaRoute = SfidaRouteImport.update({
  id: '/sfida',
  path: '/sfida',
  getParentRoute: () => rootRouteImport,
} as any)
const SfideRoute = SfideRouteImport.update({
  id: '/sfide',
  path: '/sfide',
  getParentRoute: () => rootRouteImport,
} as any)
const GiocatoriSlugRoute = GiocatoriSlugRouteImport.update({
  id: '/giocatori/$slug',
  path: '/giocatori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SHostGuestRoute = SHostGuestRouteImport.update({
  id: '/s/$host/$guest',
  path: '/s/$host/$guest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rosa': typeof RosaRoute
  '/sfida': typeof SfidaRoute
  '/sfide': typeof SfideRoute
  '/giocatori/$slug': typeof GiocatoriSlugRoute
  '/s/$id': typeof SIdRoute
  '/s/$host/$guest': typeof SHostGuestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rosa': typeof RosaRoute
  '/sfida': typeof SfidaRoute
  '/sfide': typeof SfideRoute
  '/giocatori/$slug': typeof GiocatoriSlugRoute
  '/s/$id': typeof SIdRoute
  '/s/$host/$guest': typeof SHostGuestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rosa': typeof RosaRoute
  '/sfida': typeof SfidaRoute
  '/sfide': typeof SfideRoute
  '/giocatori/$slug': typeof GiocatoriSlugRoute
  '/s/$id': typeof SIdRoute
  '/s/$host/$guest': typeof SHostGuestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rosa'
    | '/sfida'
    | '/sfide'
    | '/giocatori/$slug'
    | '/s/$id'
    | '/s/$host/$guest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rosa'
    | '/sfida'
    | '/sfide'
    | '/giocatori/$slug'
    | '/s/$id'
    | '/s/$host/$guest'
  id:
    | '__root__'
    | '/'
    | '/rosa'
    | '/sfida'
    | '/sfide'
    | '/giocatori/$slug'
    | '/s/$id'
    | '/s/$host/$guest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RosaRoute: typeof RosaRoute
  SfidaRoute: typeof SfidaRoute
  SfideRoute: typeof SfideRoute
  GiocatoriSlugRoute: typeof GiocatoriSlugRoute
  SIdRoute: typeof SIdRoute
  SHostGuestRoute: typeof SHostGuestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosa': {
      id: '/rosa'
      path: '/rosa'
      fullPath: '/rosa'
      preLoaderRoute: typeof RosaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfida': {
      id: '/sfida'
      path: '/sfida'
      fullPath: '/sfida'
      preLoaderRoute: typeof SfidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfide': {
      id: '/sfide'
      path: '/sfide'
      fullPath: '/sfide'
      preLoaderRoute: typeof SfideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giocatori/$slug': {
      id: '/giocatori/$slug'
      path: '/giocatori/$slug'
      fullPath: '/giocatori/$slug'
      preLoaderRoute: typeof GiocatoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$host/$guest': {
      id: '/s/$host/$guest'
      path: '/s/$host/$guest'
      fullPath: '/s/$host/$guest'
      preLoaderRoute: typeof SHostGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RosaRoute: RosaRoute,
  SfidaRoute: SfidaRoute,
  SfideRoute: SfideRoute,
  GiocatoriSlugRoute: GiocatoriSlugRoute,
  SIdRoute: SIdRoute,
  SHostGuestRoute: SHostGuestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
