/* generated by scripts/ingest-roster.ts — do not edit by hand */
import type { Player } from "#/lib/player";

export const players: Player[] = [
  {
    "slug": "andrea-4",
    "firstName": "Andrea",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 4,
    "birthYear": 1993,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/andrea-4.svg"
  },
  {
    "slug": "nicolo-5",
    "firstName": "Nicolò",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 5,
    "birthYear": 1993,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/nicolo-5.svg"
  },
  {
    "slug": "michele-7",
    "firstName": "Michele",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 7,
    "birthYear": 1998,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/michele-7.svg"
  },
  {
    "slug": "miriam-8",
    "firstName": "Miriam",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 8,
    "birthYear": 1997,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/miriam-8.svg"
  },
  {
    "slug": "giorgia-bomberona",
    "firstName": "Giorgia",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 10,
    "birthYear": 2002,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "bomberona",
    "photo": "players/giorgia-bomberona.svg"
  },
  {
    "slug": "federico-13",
    "firstName": "Federico",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 13,
    "birthYear": 2000,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/federico-13.svg"
  },
  {
    "slug": "alice-14",
    "firstName": "Alice",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 14,
    "birthYear": 1998,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/alice-14.svg"
  },
  {
    "slug": "andrea-23",
    "firstName": "Andrea",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 23,
    "birthYear": 1998,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/andrea-23.svg"
  },
  {
    "slug": "chiara-29",
    "firstName": "Chiara",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 29,
    "birthYear": 1994,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/chiara-29.svg"
  },
  {
    "slug": "marco-33",
    "firstName": "Marco",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 33,
    "birthYear": 1983,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/marco-33.svg"
  },
  {
    "slug": "guia-42",
    "firstName": "Guia",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 42,
    "birthYear": 2005,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/guia-42.svg"
  },
  {
    "slug": "stefano-99",
    "firstName": "Stefano",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 99,
    "birthYear": 1981,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/stefano-99.svg"
  },
  {
    "slug": "gianluca-9",
    "firstName": "Gianluca",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 9,
    "birthYear": 2005,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/gianluca-9.svg"
  },
  {
    "slug": "alex-11",
    "firstName": "Alex",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 11,
    "birthYear": 2008,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/alex-11.svg"
  },
  {
    "slug": "luca-15",
    "firstName": "Luca",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 15,
    "birthYear": 2006,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/luca-15.svg"
  },
  {
    "slug": "rebecca-18",
    "firstName": "Rebecca",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 18,
    "birthYear": 2009,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/rebecca-18.svg"
  },
  {
    "slug": "giulio-21",
    "firstName": "Giulio",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 21,
    "birthYear": 2007,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/giulio-21.svg"
  },
  {
    "slug": "marialaura-22",
    "firstName": "MariaLaura",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 22,
    "birthYear": 2009,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/marialaura-22.svg"
  },
  {
    "slug": "gabriele-28",
    "firstName": "Gabriele",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 28,
    "birthYear": 2009,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/gabriele-28.svg"
  },
  {
    "slug": "pietro-30",
    "firstName": "Pietro",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 30,
    "birthYear": 2008,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/pietro-30.svg"
  },
  {
    "slug": "veronica-39",
    "firstName": "Veronica",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 39,
    "birthYear": 2009,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/veronica-39.svg"
  },
  {
    "slug": "tommaso-67",
    "firstName": "Tommaso",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 67,
    "birthYear": 2009,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/tommaso-67.svg"
  },
  {
    "slug": "chiara-81",
    "firstName": "Chiara",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 81,
    "birthYear": 2009,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/chiara-81.svg"
  },
  {
    "slug": "guglielmo-0",
    "firstName": "Guglielmo",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 0,
    "birthYear": 2008,
    "appearances": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "photo": "players/guglielmo-0.svg"
  }
];
