/* generated by scripts/ingest-roster.ts — do not edit by hand */
import type { Player } from "#/lib/player";

export const players: Player[] = [
  {
    "slug": "andrea-papu",
    "firstName": "Andrea",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 4,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "PAPU",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "nicolo-nick",
    "firstName": "Nicolò",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 5,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Nick",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "d6b370",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "michele-costa",
    "firstName": "Michele",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 7,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Costa",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "c68e7a"
    }
  },
  {
    "slug": "miriam-nonmiribecco",
    "firstName": "Miriam",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 8,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "nonMIRibecco",
    "portrait": {
      "hair": "undercut",
      "rearHair": "longWavy",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "c68e7a"
    }
  },
  {
    "slug": "giorgia-pappagiorgia",
    "firstName": "Giorgia",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 10,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "pappagiorgia",
    "portrait": {
      "hair": "undercut",
      "rearHair": "longWavy",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "f1c3a5"
    }
  },
  {
    "slug": "federico-peppinson",
    "firstName": "Federico",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 13,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Peppinson",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "c68e7a"
    }
  },
  {
    "slug": "alice-winx",
    "firstName": "Alice",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 14,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Winx",
    "portrait": {
      "hair": "spiky",
      "rearHair": "longStraight",
      "beard": "none",
      "hairColor": "d6b370",
      "skinColor": "f1c3a5"
    }
  },
  {
    "slug": "andrea-mascotte",
    "firstName": "Andrea",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 23,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Mascotte",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "c68e7a"
    }
  },
  {
    "slug": "chiara-kia",
    "firstName": "Chiara",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 29,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "KIA",
    "portrait": {
      "hair": "undercut",
      "rearHair": "longWavy",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "marco-mt",
    "firstName": "Marco",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 33,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "MT",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "moustacheTwirl",
      "hairColor": "2c1b18",
      "skinColor": "c68e7a"
    }
  },
  {
    "slug": "guia-vaiana",
    "firstName": "Guia",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 42,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "vaiana",
    "portrait": {
      "hair": "spiky",
      "rearHair": "longStraight",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "f1c3a5"
    }
  },
  {
    "slug": "stefano-ragno",
    "firstName": "Stefano",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 99,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Ragno",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "fullBeard",
      "hairColor": "d6b370",
      "skinColor": "c68e7a"
    }
  },
  {
    "slug": "gianluca-gb",
    "firstName": "Gianluca",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 9,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "GB",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "alex-axel",
    "firstName": "Alex",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 11,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "AXEL",
    "portrait": {
      "hair": "spiky",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "d6b370",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "luca-luc-avelli",
    "firstName": "Luca",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 15,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Luc'Avelli",
    "portrait": {
      "hair": "undercut",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "d6b370",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "rebecca-quechua",
    "firstName": "Rebecca",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 18,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Quechua",
    "portrait": {
      "hair": "undercut",
      "rearHair": "longWavy",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "f1c3a5"
    }
  },
  {
    "slug": "giulio-j-tata",
    "firstName": "Giulio",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 21,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "J-TATA",
    "portrait": {
      "hair": "bun",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "f1c3a5"
    }
  },
  {
    "slug": "marialaura-baguette",
    "firstName": "MariaLaura",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 22,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Baguette",
    "portrait": {
      "hair": "spiky",
      "rearHair": "longStraight",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "gabriele-gabbo",
    "firstName": "Gabriele",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 28,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Gabbo",
    "portrait": {
      "hair": "spiky",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "pietro-della",
    "firstName": "Pietro",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 30,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "DELLA",
    "portrait": {
      "hair": "undercut",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "d6b370",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "veronica-vero",
    "firstName": "Veronica",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 93,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Vero",
    "portrait": {
      "hair": "undercut",
      "rearHair": "longWavy",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "tommaso-tommygamer",
    "firstName": "Tommaso",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 67,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "TommyGamer",
    "portrait": {
      "hair": "spiky",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "d6b370",
      "skinColor": "f1c3a5"
    }
  },
  {
    "slug": "chiara-81",
    "firstName": "Chiara",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 81,
    "overall": 77,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 85,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "portrait": {
      "hair": "undercut",
      "rearHair": "longWavy",
      "beard": "none",
      "hairColor": "2c1b18",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "guglielmo-google",
    "firstName": "Guglielmo",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "GOOGLE",
    "portrait": {
      "hair": "spiky",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "c68e7a"
    }
  },
  {
    "slug": "ga-ga",
    "firstName": "Ga",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 24,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Ga",
    "portrait": {
      "hair": "spiky",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "5c3829"
    }
  },
  {
    "slug": "mordecai-mordecai",
    "firstName": "MORDECAI",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 6,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "MORDECAI",
    "portrait": {
      "hair": "spiky",
      "rearHair": "none",
      "beard": "none",
      "hairColor": "724133",
      "skinColor": "c68e7a"
    }
  }
];
