/* generated by scripts/ingest-roster.ts — do not edit by hand */
import type { Player } from "#/lib/player";

export const players: Player[] = [
  {
    "slug": "andrea-papu",
    "firstName": "Andrea",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 4,
    "birthYear": 1993,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "PAPU"
  },
  {
    "slug": "nicolo-nick",
    "firstName": "Nicolò",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 5,
    "birthYear": 1993,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Nick"
  },
  {
    "slug": "michele-costa",
    "firstName": "Michele",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 7,
    "birthYear": 1998,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Costa"
  },
  {
    "slug": "miriam-nonmiribecco",
    "firstName": "Miriam",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 8,
    "birthYear": 1997,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "nonMIRibecco"
  },
  {
    "slug": "giorgia-pappagiorgia",
    "firstName": "Giorgia",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 10,
    "birthYear": 2002,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "pappagiorgia",
    "portrait": {
      "hair": "undercut",
      "rearHair": "longWavy",
      "beard": "none",
      "skinColor": "f1c3a5"
    }
  },
  {
    "slug": "federico-peppinson",
    "firstName": "Federico",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 13,
    "birthYear": 2000,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Peppinson"
  },
  {
    "slug": "alice-winx",
    "firstName": "Alice",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 14,
    "birthYear": 1998,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Winx"
  },
  {
    "slug": "andrea-mascotte",
    "firstName": "Andrea",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 23,
    "birthYear": 1998,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Mascotte"
  },
  {
    "slug": "chiara-kia",
    "firstName": "Chiara",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 29,
    "birthYear": 1994,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "KIA"
  },
  {
    "slug": "marco-mt",
    "firstName": "Marco",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 33,
    "birthYear": 1983,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "MT"
  },
  {
    "slug": "guia-vaiana",
    "firstName": "Guia",
    "team": "Saccho's Team",
    "sex": "F",
    "number": 42,
    "birthYear": 2005,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "vaiana"
  },
  {
    "slug": "stefano-ragno",
    "firstName": "Stefano",
    "team": "Saccho's Team",
    "sex": "M",
    "number": 99,
    "birthYear": 1981,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Ragno",
    "portrait": {
      "hair": "sideComed",
      "rearHair": "none",
      "beard": "fullBeard",
      "skinColor": "c68e7a"
    }
  },
  {
    "slug": "gianluca-gb",
    "firstName": "Gianluca",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 9,
    "birthYear": 2005,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "GB"
  },
  {
    "slug": "alex-axel",
    "firstName": "Alex",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 11,
    "birthYear": 2008,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "AXEL"
  },
  {
    "slug": "luca-luc-avelli",
    "firstName": "Luca",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 15,
    "birthYear": 2006,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Luc'Avelli"
  },
  {
    "slug": "rebecca-quechua",
    "firstName": "Rebecca",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 18,
    "birthYear": 2009,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Quechua"
  },
  {
    "slug": "giulio-j-tata",
    "firstName": "Giulio",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 21,
    "birthYear": 2007,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "J-TATA"
  },
  {
    "slug": "marialaura-baguette",
    "firstName": "MariaLaura",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 22,
    "birthYear": 2009,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Baguette"
  },
  {
    "slug": "gabriele-gabbo",
    "firstName": "Gabriele",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 28,
    "birthYear": 2009,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Gabbo"
  },
  {
    "slug": "pietro-della",
    "firstName": "Pietro",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 30,
    "birthYear": 2008,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "DELLA"
  },
  {
    "slug": "veronica-vero",
    "firstName": "Veronica",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 93,
    "birthYear": 2009,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Vero"
  },
  {
    "slug": "tommaso-tommygamer",
    "firstName": "Tommaso",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 67,
    "birthYear": 2009,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "TommyGamer"
  },
  {
    "slug": "chiara-81",
    "firstName": "Chiara",
    "team": "Saccios Tim",
    "sex": "F",
    "number": 81,
    "birthYear": 2009,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    }
  },
  {
    "slug": "guglielmo-google",
    "firstName": "Guglielmo",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 0,
    "birthYear": 2008,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "GOOGLE",
    "portrait": {
      "hair": "spiky",
      "rearHair": "none",
      "beard": "none"
    }
  },
  {
    "slug": "ga-ga",
    "firstName": "Ga",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 24,
    "birthYear": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "Ga"
  },
  {
    "slug": "mordecai-mordecai",
    "firstName": "MORDECAI",
    "team": "Saccios Tim",
    "sex": "M",
    "number": 6,
    "birthYear": 0,
    "overall": 75,
    "stats": {
      "velocita": 75,
      "salto": 75,
      "intercetto": 75,
      "scalpo": 75,
      "finalizzazione": 75,
      "gk": 75
    },
    "nickname": "MORDECAI"
  }
];
